contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #srnapipe channel"
    url: https://nfcore.slack.com/channels/srnapipe
    about: Discussion about the nf-core/srnapipe pipeline
